-- Tabla para historial de actividades financieras
CREATE TABLE public.app_cont_historial_actividades (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tipo_actividad character varying NOT NULL, -- 'gasto_registrado', 'gasto_eliminado', 'operacion_procesada', etc.
  descripcion text NOT NULL,
  entidad_tipo character varying NOT NULL, -- 'gasto', 'operacion', 'asignacion', etc.
  entidad_id bigint NULL, -- ID de la entidad relacionada
  monto numeric NULL, -- Monto involucrado si aplica
  usuario_id uuid NOT NULL,
  id_tienda bigint NOT NULL,
  metadata jsonb NULL, -- Información adicional en formato JSON
  fecha_actividad timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  CONSTRAINT app_cont_historial_actividades_pkey PRIMARY KEY (id),
  CONSTRAINT app_cont_historial_actividades_usuario_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id),
  CONSTRAINT app_cont_historial_actividades_tienda_fkey FOREIGN KEY (id_tienda) REFERENCES app_dat_tienda(id),
  
  -- Constraints para validar tipos de actividad
  CONSTRAINT app_cont_historial_actividades_tipo_check CHECK (
    tipo_actividad IN (
      'gasto_registrado', 'gasto_eliminado', 'gasto_actualizado',
      'operacion_procesada', 'operacion_omitida', 'operacion_eliminada',
      'asignacion_creada', 'asignacion_actualizada', 'asignacion_eliminada',
      'categoria_creada', 'categoria_actualizada', 'categoria_eliminada',
      'centro_costo_creado', 'centro_costo_actualizado', 'centro_costo_eliminado',
      'tipo_costo_creado', 'tipo_costo_actualizado', 'tipo_costo_eliminado',
      'sistema_inicializado', 'configuracion_actualizada'
    )
  ),
  
  CONSTRAINT app_cont_historial_actividades_entidad_check CHECK (
    entidad_tipo IN ('gasto', 'operacion', 'asignacion', 'categoria', 'subcategoria', 'centro_costo', 'tipo_costo', 'sistema')
  )
) TABLESPACE pg_default;

-- Índices para optimizar consultas
CREATE INDEX IF NOT EXISTS idx_historial_actividades_fecha ON public.app_cont_historial_actividades 
USING btree (fecha_actividad DESC) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_historial_actividades_tienda_fecha ON public.app_cont_historial_actividades 
USING btree (id_tienda, fecha_actividad DESC) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_historial_actividades_tipo ON public.app_cont_historial_actividades 
USING btree (tipo_actividad) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_historial_actividades_entidad ON public.app_cont_historial_actividades 
USING btree (entidad_tipo, entidad_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_historial_actividades_usuario ON public.app_cont_historial_actividades 
USING btree (usuario_id) TABLESPACE pg_default;

-- Índice compuesto para consultas comunes
CREATE INDEX IF NOT EXISTS idx_historial_actividades_tienda_tipo_fecha ON public.app_cont_historial_actividades 
USING btree (id_tienda, tipo_actividad, fecha_actividad DESC) TABLESPACE pg_default;

-- Comentarios para documentación
COMMENT ON TABLE public.app_cont_historial_actividades IS 'Historial de todas las actividades realizadas en el módulo financiero';
COMMENT ON COLUMN public.app_cont_historial_actividades.tipo_actividad IS 'Tipo de actividad realizada (gasto_registrado, operacion_procesada, etc.)';
COMMENT ON COLUMN public.app_cont_historial_actividades.descripcion IS 'Descripción legible de la actividad realizada';
COMMENT ON COLUMN public.app_cont_historial_actividades.entidad_tipo IS 'Tipo de entidad sobre la que se realizó la actividad';
COMMENT ON COLUMN public.app_cont_historial_actividades.entidad_id IS 'ID de la entidad específica (puede ser NULL para actividades generales)';
COMMENT ON COLUMN public.app_cont_historial_actividades.metadata IS 'Información adicional en formato JSON (valores anteriores, detalles, etc.)';
