-- Crear tabla para denominaciones de moneda
CREATE TABLE public.app_dat_denominaciones_moneda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_moneda VARCHAR(10) NOT NULL,
    denominacion NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT app_dat_denominaciones_moneda_pkey PRIMARY KEY (id)
);

-- Crear índices para optimizar consultas
CREATE INDEX idx_denominaciones_moneda_codigo ON public.app_dat_denominaciones_moneda(codigo_moneda);
CREATE INDEX idx_denominaciones_moneda_active ON public.app_dat_denominaciones_moneda(active);
CREATE INDEX idx_denominaciones_moneda_codigo_active ON public.app_dat_denominaciones_moneda(codigo_moneda, active);

-- Trigger para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_denominaciones_moneda_updated_at 
    BEFORE UPDATE ON public.app_dat_denominaciones_moneda 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insertar denominaciones por defecto para USD
INSERT INTO public.app_dat_denominaciones_moneda (codigo_moneda, denominacion) VALUES
('USD', 1),
('USD', 5),
('USD', 10),
('USD', 20),
('USD', 50),
('USD', 100);

-- Insertar denominaciones por defecto para CUP
INSERT INTO public.app_dat_denominaciones_moneda (codigo_moneda, denominacion) VALUES
('CUP', 1),
('CUP', 3),
('CUP', 5),
('CUP', 10),
('CUP', 20),
('CUP', 50),
('CUP', 100),
('CUP', 200),
('CUP', 500),
('CUP', 1000);

-- Insertar denominaciones por defecto para EUR
INSERT INTO public.app_dat_denominaciones_moneda (codigo_moneda, denominacion) VALUES
('EUR', 5),
('EUR', 10),
('EUR', 20),
('EUR', 50),
('EUR', 100),
('EUR', 200),
('EUR', 500);

-- Insertar denominaciones por defecto para MLC
INSERT INTO public.app_dat_denominaciones_moneda (codigo_moneda, denominacion) VALUES
('MLC', 1),
('MLC', 5),
('MLC', 10),
('MLC', 20),
('MLC', 50),
('MLC', 100);

-- Comentarios para documentación
COMMENT ON TABLE public.app_dat_denominaciones_moneda IS 'Tabla para almacenar las denominaciones de billetes por moneda';
COMMENT ON COLUMN public.app_dat_denominaciones_moneda.codigo_moneda IS 'Código de la moneda (USD, CUP, EUR, MLC, etc.)';
COMMENT ON COLUMN public.app_dat_denominaciones_moneda.denominacion IS 'Valor de la denominación del billete';
COMMENT ON COLUMN public.app_dat_denominaciones_moneda.active IS 'Indica si la denominación está activa para uso';

-- Configurar RLS (Row Level Security) si es necesario
ALTER TABLE public.app_dat_denominaciones_moneda ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura a usuarios autenticados
CREATE POLICY "Permitir lectura de denominaciones a usuarios autenticados" 
ON public.app_dat_denominaciones_moneda FOR SELECT 
TO authenticated 
USING (true);

-- Política para permitir inserción/actualización solo a administradores
CREATE POLICY "Permitir modificación de denominaciones solo a administradores" 
ON public.app_dat_denominaciones_moneda FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM auth.users u 
        WHERE u.id = auth.uid() 
        AND u.raw_user_meta_data->>'role' IN ('Gerente', 'Supervisor')
    )
);
