create table public.app_suscripciones (
  id bigint generated always as identity not null,
  id_tienda bigint not null,
  id_plan smallint not null,
  fecha_inicio timestamp with time zone not null default now(),
  fecha_fin timestamp with time zone null,
  estado smallint not null default 1,
  metodo_pago character varying null,
  id_pago_externo character varying null,
  creado_por uuid not null,
  renovacion_automatica boolean null default false,
  observaciones text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  gestionado_por text null,
  constraint app_suscripciones_pkey primary key (id),
  constraint app_suscripciones_creado_por_fkey foreign KEY (creado_por) references auth.users (id),
  constraint app_suscripciones_id_plan_fkey foreign KEY (id_plan) references app_suscripciones_plan (id),
  constraint app_suscripciones_id_tienda_fkey foreign KEY (id_tienda) references app_dat_tienda (id)
) TABLESPACE pg_default;

create index IF not exists idx_app_suscripciones_tienda on public.app_suscripciones using btree (id_tienda) TABLESPACE pg_default;

create index IF not exists idx_app_suscripciones_estado on public.app_suscripciones using btree (estado) TABLESPACE pg_default;




create table public.app_suscripciones_plan (
  id smallint generated always as identity not null,
  denominacion character varying not null,
  descripcion text null,
  precio_mensual numeric not null,
  duracion_trial_dias integer not null default 15,
  limite_tiendas smallint null default 1,
  limite_usuarios smallint null default 5,
  funciones_habilitadas jsonb null,
  es_activo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  periodo smallint not null default '1'::smallint,
  moneda text not null default 'USD'::text,
  constraint app_suscripciones_plan_pkey primary key (id)
) TABLESPACE pg_default;

create table public.app_dat_suscripcion_catalogo (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_tienda bigint null,
  tiempo_suscripcion numeric null,
  vencido boolean null,
  constraint app_dat_suscripcion_catalogo_pkey primary key (id)
) TABLESPACE pg_default;

create or replace function public.trg_app_suscripciones_insert_catalogo()
returns trigger
language plpgsql
as $$
declare
  v_duracion_dias int;
begin
  if tg_op = 'UPDATE' then
    if new.fecha_inicio is null
      or old.fecha_inicio is null
      or new.fecha_inicio <= old.fecha_inicio then
      return new;
    end if;
  end if;

  if new.id_plan in (1, 2, 3, 4) then
    v_duracion_dias := 30;
  elsif new.id_plan = 5 then
    v_duracion_dias := 360;
  else
    return new;
  end if;

  perform 1
  from public.app_dat_suscripcion_catalogo c
  where c.id_tienda = new.id_tienda
    and coalesce(c.vencido, false) = false
    and now() < c.created_at + make_interval(days => coalesce(c.tiempo_suscripcion, 0)::int)
  limit 1;

  if found then
    return new;
  end if;

  insert into public.app_dat_suscripcion_catalogo (
    id_tienda,
    tiempo_suscripcion,
    vencido
  )
  values (
    new.id_tienda,
    v_duracion_dias,
    false
  );

  return new;
end;
$$;

drop trigger if exists trg_app_suscripciones_catalogo on public.app_suscripciones;

create trigger trg_app_suscripciones_catalogo
after insert or update of fecha_inicio on public.app_suscripciones
for each row
execute function public.trg_app_suscripciones_insert_catalogo();